### ISSUE TITLE
disable streaming for bot UAs by default, optionally disable streaming per page

### ISSUE THREAD

**Issue by acao** [XiNiHa/vilay#30]
1. would be good to disable streaming for bot user agents by default, but allow users to override this globally or per page if they want. We can achieve this without UA parsing of course
2. it would be great to be able to optionally disable streaming per page, and/or configure other modes. the [UMR spec](https://github.com/fastify/fastify-dx/blob/main/URMA.md) has some ideas for this, each framework does it a different way

**Comment by XiNiHa** [comment]
AFAIK it's already implemented by using `react-streaming`. If it doesn't, it should be considered as a bug I guess

**Comment by acao** [comment]
ah of course, I should know, I learned about this pattern from the `react-streaming` source!
